###############################################################################
# cuda:11.0-devel-centos8.1.1911                                                 #
###############################################################################
FROM centos:8.1.1911

# install epel repository
RUN dnf makecache
# RUN dnf -y update # skip
RUN dnf -y install wget 

# get cuda11 rpm file
RUN mkdir -p /tmp/cuda11
COPY cuda-repo-rhel8-11-0-local-11.0.0_2020.1.2.52-1.aarch64.rpm /tmp/cuda11

# install cuda11 repository
RUN cd /tmp/cuda11 && \
    dnf -y install ./cuda-repo-rhel8-11-0-local-11.0.0_2020.1.2.52-1.aarch64.rpm

# install cuda11
RUN dnf -y makecache && \
    dnf -y install \
      cuda-cudart-11-0 \
      cuda-compat-11-0 \
      cuda-libraries-devel-11-0 \
      cuda-nvml-devel-11-0 \
      cuda-minimal-build-11-0 \
      cuda-command-line-tools-11-0 \
      cuda-compiler-11-0 cuda-nvcc-11-0 \
      libcusolver-11-0 \
      cuda-toolkit-11-0

# cleanup
RUN rm -rf /var/cuda-repo-rhel8-11-0-local && \
    rm -rf /etc/yum.repos.d/cuda-rhel8-11-0-local.repo && \
    rm -rf /tmp/cuda11
RUN dnf clean all

# update ld.so.conf # skip not needed
#RUN echo "/usr/local/cuda-11.0/targets/sbsa-linux/lib" > /etc/ld.so.conf.d/cuda-11-0.conf

# create soft links # skip not needed
#RUN ln -s /usr/local/cuda-11.0 /usr/local/cuda

# update environment
ENV PATH=/usr/local/cuda/bin:$PATH
ENV LD_LIBRARY_PATH=/usr/local/cuda/targets/sbsa-linux/lib:$LD_LIBRARY_PATH
ENV LIBRARY_PATH /usr/local/cuda/lib64/stubs
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
